// Code generated by "stringer -type=OperandType"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OT_Exact-0]
	_ = x[OT_Register32-1]
	_ = x[OT_Register64-2]
	_ = x[OT_ImmediateValue-3]
}

const _OperandType_name = "OT_ExactOT_Register32OT_Register64OT_ImmediateValue"

var _OperandType_index = [...]uint8{0, 8, 21, 34, 51}

func (i OperandType) String() string {
	if i < 0 || i >= OperandType(len(_OperandType_index)-1) {
		return "OperandType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperandType_name[_OperandType_index[i]:_OperandType_index[i+1]]
}
