// Code generated by "stringer -type=OperandEncoding"; DO NOT EDIT.

package encoding

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModRM_rm_r-0]
	_ = x[ModRM_rm_rw-1]
	_ = x[ModRM_reg_r-2]
	_ = x[ModRM_reg_rw-3]
	_ = x[ImmediateValue-4]
}

const _OperandEncoding_name = "ModRM_rm_rModRM_rm_rwModRM_reg_rModRM_reg_rwImmediateValue"

var _OperandEncoding_index = [...]uint8{0, 10, 21, 32, 44, 58}

func (i OperandEncoding) String() string {
	if i < 0 || i >= OperandEncoding(len(_OperandEncoding_index)-1) {
		return "OperandEncoding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OperandEncoding_name[_OperandEncoding_index[i]:_OperandEncoding_index[i+1]]
}
