// Code generated by "stringer -type=ELFClass"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ELFCLASSNONE-0]
	_ = x[ELFCLASS32-1]
	_ = x[ELFCLASS64-2]
	_ = x[ELFCLASSNUM-3]
}

const _ELFClass_name = "ELFCLASSNONEELFCLASS32ELFCLASS64ELFCLASSNUM"

var _ELFClass_index = [...]uint8{0, 12, 22, 32, 43}

func (i ELFClass) String() string {
	if i >= ELFClass(len(_ELFClass_index)-1) {
		return "ELFClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELFClass_name[_ELFClass_index[i]:_ELFClass_index[i+1]]
}
