// Code generated by "stringer -type=ELFMachine"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EM_NONE-0]
	_ = x[EM_M32-1]
	_ = x[EM_SPARC-2]
	_ = x[EM_386-3]
	_ = x[EM_68K-4]
	_ = x[EM_88K-5]
	_ = x[EM_860-7]
	_ = x[EM_MIPS-8]
	_ = x[EM_PPC-20]
	_ = x[EM_PPC64-21]
	_ = x[EM_ARM-40]
	_ = x[EM_X86_64-62]
}

const (
	_ELFMachine_name_0 = "EM_NONEEM_M32EM_SPARCEM_386EM_68KEM_88K"
	_ELFMachine_name_1 = "EM_860EM_MIPS"
	_ELFMachine_name_2 = "EM_PPCEM_PPC64"
	_ELFMachine_name_3 = "EM_ARM"
	_ELFMachine_name_4 = "EM_X86_64"
)

var (
	_ELFMachine_index_0 = [...]uint8{0, 7, 13, 21, 27, 33, 39}
	_ELFMachine_index_1 = [...]uint8{0, 6, 13}
	_ELFMachine_index_2 = [...]uint8{0, 6, 14}
)

func (i ELFMachine) String() string {
	switch {
	case i <= 5:
		return _ELFMachine_name_0[_ELFMachine_index_0[i]:_ELFMachine_index_0[i+1]]
	case 7 <= i && i <= 8:
		i -= 7
		return _ELFMachine_name_1[_ELFMachine_index_1[i]:_ELFMachine_index_1[i+1]]
	case 20 <= i && i <= 21:
		i -= 20
		return _ELFMachine_name_2[_ELFMachine_index_2[i]:_ELFMachine_index_2[i+1]]
	case i == 40:
		return _ELFMachine_name_3
	case i == 62:
		return _ELFMachine_name_4
	default:
		return "ELFMachine(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
