// Code generated by "stringer -type=ELFOS_ABI"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ELF_OS_ABI_NONE-0]
	_ = x[ELF_OS_ABI_LINUX-3]
}

const (
	_ELFOS_ABI_name_0 = "ELF_OS_ABI_NONE"
	_ELFOS_ABI_name_1 = "ELF_OS_ABI_LINUX"
)

func (i ELFOS_ABI) String() string {
	switch {
	case i == 0:
		return _ELFOS_ABI_name_0
	case i == 3:
		return _ELFOS_ABI_name_1
	default:
		return "ELFOS_ABI(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
