// Code generated by "stringer -type=ELFType"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ET_NONE-0]
	_ = x[ET_REL-1]
	_ = x[ET_EXEC-2]
	_ = x[ET_DYN-3]
	_ = x[ET_CORE-4]
	_ = x[ET_LOPROC-65280]
	_ = x[ET_HIPROC-65535]
}

const (
	_ELFType_name_0 = "ET_NONEET_RELET_EXECET_DYNET_CORE"
	_ELFType_name_1 = "ET_LOPROC"
	_ELFType_name_2 = "ET_HIPROC"
)

var (
	_ELFType_index_0 = [...]uint8{0, 7, 13, 20, 26, 33}
)

func (i ELFType) String() string {
	switch {
	case i <= 4:
		return _ELFType_name_0[_ELFType_index_0[i]:_ELFType_index_0[i+1]]
	case i == 65280:
		return _ELFType_name_1
	case i == 65535:
		return _ELFType_name_2
	default:
		return "ELFType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
