// Code generated by "stringer -type=ELFVersion"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EV_NONE-0]
	_ = x[EV_CURRENT-1]
}

const _ELFVersion_name = "EV_NONEEV_CURRENT"

var _ELFVersion_index = [...]uint8{0, 7, 17}

func (i ELFVersion) String() string {
	if i >= ELFVersion(len(_ELFVersion_index)-1) {
		return "ELFVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ELFVersion_name[_ELFVersion_index[i]:_ELFVersion_index[i+1]]
}
