// Code generated by "stringer -type=PHType"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PT_NULL-0]
	_ = x[PT_LOAD-1]
	_ = x[PT_DYNAMIC-2]
	_ = x[PT_INTERP-3]
	_ = x[PT_NOTE-4]
	_ = x[PT_SHLIB-5]
	_ = x[PT_PHDR-6]
	_ = x[PT_LOPROC-1879048192]
	_ = x[PT_HIPROC-2147483647]
}

const (
	_PHType_name_0 = "PT_NULLPT_LOADPT_DYNAMICPT_INTERPPT_NOTEPT_SHLIBPT_PHDR"
	_PHType_name_1 = "PT_LOPROC"
	_PHType_name_2 = "PT_HIPROC"
)

var (
	_PHType_index_0 = [...]uint8{0, 7, 14, 24, 33, 40, 48, 55}
)

func (i PHType) String() string {
	switch {
	case i <= 6:
		return _PHType_name_0[_PHType_index_0[i]:_PHType_index_0[i+1]]
	case i == 1879048192:
		return _PHType_name_1
	case i == 2147483647:
		return _PHType_name_2
	default:
		return "PHType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
