// Code generated by "stringer -type=SHFlags"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SHF_NULL-0]
	_ = x[SHF_WRITE-1]
	_ = x[SHF_ALLOC-2]
	_ = x[SHF_EXECINSTR-4]
	_ = x[SHF_RELA_LIVEPATCH-1048576]
	_ = x[SHF_RO_AFTER_INIT-2097152]
	_ = x[SHF_MASKPROC-4026531840]
}

const (
	_SHFlags_name_0 = "SHF_NULLSHF_WRITESHF_ALLOC"
	_SHFlags_name_1 = "SHF_EXECINSTR"
	_SHFlags_name_2 = "SHF_RELA_LIVEPATCH"
	_SHFlags_name_3 = "SHF_RO_AFTER_INIT"
	_SHFlags_name_4 = "SHF_MASKPROC"
)

var (
	_SHFlags_index_0 = [...]uint8{0, 8, 17, 26}
)

func (i SHFlags) String() string {
	switch {
	case i <= 2:
		return _SHFlags_name_0[_SHFlags_index_0[i]:_SHFlags_index_0[i+1]]
	case i == 4:
		return _SHFlags_name_1
	case i == 1048576:
		return _SHFlags_name_2
	case i == 2097152:
		return _SHFlags_name_3
	case i == 4026531840:
		return _SHFlags_name_4
	default:
		return "SHFlags(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
