// Code generated by "stringer -type=SymbolBinding"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SB_LOCAL-0]
	_ = x[SB_GLOBAL-1]
	_ = x[SB_WEAK-2]
	_ = x[SB_LOPROC-13]
	_ = x[SB_HIPROC-15]
}

const (
	_SymbolBinding_name_0 = "SB_LOCALSB_GLOBALSB_WEAK"
	_SymbolBinding_name_1 = "SB_LOPROC"
	_SymbolBinding_name_2 = "SB_HIPROC"
)

var (
	_SymbolBinding_index_0 = [...]uint8{0, 8, 17, 24}
)

func (i SymbolBinding) String() string {
	switch {
	case i <= 2:
		return _SymbolBinding_name_0[_SymbolBinding_index_0[i]:_SymbolBinding_index_0[i+1]]
	case i == 13:
		return _SymbolBinding_name_1
	case i == 15:
		return _SymbolBinding_name_2
	default:
		return "SymbolBinding(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
