// Code generated by "stringer -type=SymbolType"; DO NOT EDIT.

package elf

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[STT_NOTYPE-0]
	_ = x[STT_OBJECT-1]
	_ = x[STT_FUNC-2]
	_ = x[STT_SECTION-3]
	_ = x[STT_FILE-4]
	_ = x[STT_LOPROC-13]
	_ = x[STT_HIPROC-15]
}

const (
	_SymbolType_name_0 = "STT_NOTYPESTT_OBJECTSTT_FUNCSTT_SECTIONSTT_FILE"
	_SymbolType_name_1 = "STT_LOPROC"
	_SymbolType_name_2 = "STT_HIPROC"
)

var (
	_SymbolType_index_0 = [...]uint8{0, 10, 20, 28, 39, 47}
)

func (i SymbolType) String() string {
	switch {
	case i <= 4:
		return _SymbolType_name_0[_SymbolType_index_0[i]:_SymbolType_index_0[i+1]]
	case i == 13:
		return _SymbolType_name_1
	case i == 15:
		return _SymbolType_name_2
	default:
		return "SymbolType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
