// Code generated by "stringer -type=TypeNr"; DO NOT EDIT.

package shared

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[T_Uint8-0]
	_ = x[T_Uint64-1]
	_ = x[T_Float64-2]
	_ = x[T_Bool-3]
	_ = x[T_Array-4]
	_ = x[T_Function-5]
}

const _TypeNr_name = "T_Uint8T_Uint64T_Float64T_BoolT_ArrayT_Function"

var _TypeNr_index = [...]uint8{0, 7, 15, 24, 30, 37, 47}

func (i TypeNr) String() string {
	if i < 0 || i >= TypeNr(len(_TypeNr_index)-1) {
		return "TypeNr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TypeNr_name[_TypeNr_index[i]:_TypeNr_index[i+1]]
}
